---
output: 
  pdf_document: 
    fig_height: 3.5
    fig_width: 4.5
geometry: margin=0.5in
---

```{r options, echo=FALSE}
library(knitr)
opts_chunk$set(cache=TRUE, echo=FALSE, warning =  FALSE, message= FALSE)
```

```{r pkgs, echo = FALSE}
library(shiny)
library(ggplot2)
library(MASS)
library(poweRlaw)
library(DT)
library(reshape2)
library(dplyr)
library(parallel)
library(moments)
library(xtable)

library(sp)
library(cartography)
library(maps)
library(markdown)

library(ggthemes)
library(scales)
library(ggrepel)
library(gridExtra)

load("data/countriesPop.RData")

BRICS <- BRICS %>% mutate(sysYear = paste(system, "\n(", year, ")", sep = ""))
```

```{r theme_gibratdc}

theme_gibratdc <- function(base_size = 11, base_family = "serif", ticks = TRUE) {
    ## TODO: start with theme_minimal
    ret <- theme_bw(base_family = base_family, base_size = base_size) +
        theme(legend.background = element_blank(),
              legend.key = element_blank(),
              panel.background = element_blank(),
              panel.border = element_blank(),
              strip.background = element_blank(),
              plot.background = element_blank(),
              panel.grid = element_blank(),
              axis.line.x = element_line(colour = "black", size = 0.3),
              axis.line.y = element_line(colour = "black", size = 0.3),
              axis.text.x = element_text(angle=45, vjust=1, hjust = 1, size = 7),
              axis.text.y = element_text(angle=45, vjust=1, hjust = 0.5, size = 7))
    if (!ticks) {
        ret <- ret + theme(axis.ticks = element_blank())
    }
    ret
}
```

Évolution des rangs-tailles
```{r prepRT_Evol, echo =FALSE, }
rtBRICS <- BRICS %>%
    filter(pop > 10E3, !is.na(pop))%>%
    group_by(system, year) %>%
  mutate(Rank = row_number(desc(pop)))
```

```{r format_si}
format_si <- function(...) {
  function(x) {
    limits <- c(1e-24, 1e-21, 1e-18, 1e-15, 1e-12,
                1e-9,  1e-6,  1e-3,  1e0,   1e3,
                1e6,   1e9,   1e12,  1e15,  1e18,
                1e21,  1e24)
    prefix <- c("y",   "z",   "a",   "f",   "p",
                "n",   "µ",   "m",   " ",   "k",
                "M",   "G",   "T",   "P",   "E",
                "Z",   "Y")
    # Vector with array indices according to position in intervals
    i <- findInterval(abs(x), limits)
 
    # Set prefix to " " for very small values < 1e-24
    i <- ifelse(i==0, which(limits == 1e0), i)

    paste(format(round(x/limits[i], 1),
                 trim=TRUE, scientific=FALSE, ...),
          prefix[i])
  }
}
```


```{r plotRT_Evol}

base_breaks <- function(n = 20){
    function(x) {
        axisTicks(log10(range(x, na.rm = TRUE)), log = TRUE, n = n)
    }
}

ggplot(rtBRICS, aes(Rank, pop, group=year, colour=year, alpha=year)) +
    geom_line(size=0.1) +
    geom_point(size=0.1) +
    scale_colour_gradient(name = "Year", low = "lightgrey", high = "black")+
    scale_alpha_continuous(name = "Year",range= c(0.4, 1), guide = FALSE) +
    facet_wrap(~system, scale="free_x", nrow=2) +
    scale_x_log10() + scale_y_log10(labels = format_si(), breaks = base_breaks(n=4)) +
    ggtitle("Rank-Size of systems across time ") +
    xlab("Rank") +
    ylab("Population")+
    theme_tufte()+
    theme(legend.position="bottom",
          legend.text = element_text(angle = 45, hjust = 1),
          #legend.title = element_blank(),
          legend.key.width=unit(2,"cm"),
          panel.margin = unit(0.1, "lines"))
```

Comparaison des rangs-tailles

```{r prepRT_Tous}
maxyear <- BRICS %>%
    group_by(system) %>%
    summarise(yearmax = max(year))

lastPops <- BRICS %>%
    semi_join(maxyear, by = c("system",  "year" = "yearmax")) %>%
    filter(pop > 10E3,!is.na(pop))

rtLastPops <- lastPops %>%
    group_by(system, year) %>%
  mutate(Rank = row_number(desc(pop)))
```

```{r plotRT_Tous}
ggplot(rtLastPops, aes(Rank, pop, group=system, colour=system, linetype = system)) +
    geom_line(size=0.5) +
    scale_color_grey(start = 0.25, end = 0.5, guide = FALSE) +
    scale_linetype_discrete(name = "System",  guide =  FALSE) +
    scale_x_log10(breaks=base_breaks(), labels = format_si()) + scale_y_log10(breaks=base_breaks(), labels = format_si()) +
    ggtitle("Rank-Size of systems at last census date ") +
    xlab("Rank") +
    ylab("Population")+
    theme_tufte()+
    geom_label_repel(
        data = filter(rtLastPops, Rank == max(Rank)),
        aes(label = system),
        size = 3,
        segment.color = "black",segment.size = 0.2
    ) +
    theme(axis.line = element_line(colour = "black", size= 1, linetype= "solid"))
```


Histogrammes & QQplots

```{r prepHisto}

histLastPops <- lastPops %>%
    filter(system %in% c("Brazil", "Europe", "India")) %>%
    mutate(logpop = log10(pop)) %>%
    mutate(sklogpop = log10(pop - 10E3)) %>%
    mutate(skpop = pop - 10E3) %>%
    filter(skpop > 1) %>%
    group_by(system) %>%
    mutate(meanLog = mean(sklogpop)) %>%
    mutate(sdLog = sd(sklogpop))
  
logLabel <- function(x){
   (10^x) + 10E3
}
```


```{r plotHist}
customBreaks <- log10(c(10,15E3, 90E3, 990E3, 9990E3))
 customLabels <- format_si()(c(10E3, 25E3, 100E3, 1E6, 10E6))
 
  histPlots <- lapply(split(histLastPops,histLastPops$sysYear),FUN=function(state_slice){ 
     ggplot(state_slice, aes(sklogpop)) + 
         geom_histogram(aes(y = ..density..), fill = 'grey70', colour = "grey75",  bins = 30) +
         geom_density(color="grey10", size=0.2) +
         stat_function(color="black", linetype = "dashed", size=0.3,fun=dnorm,
                       args=list(
                           mean=state_slice$meanLog[1],
                           sd=state_slice$sdLog[1])) +
         scale_x_continuous(name = "", labels = customLabels, breaks = customBreaks) +
         scale_y_continuous(name="") +
         ggtitle(unique(state_slice$sysYear)) +
         theme_gibratdc() +
         theme(axis.title = element_blank())
 })
 
 grid.arrange(grobs = histPlots, bottom = "Population",
              left = "Density",
              nrow=1)
```

```{r plotQQ}
 qqPlots <- lapply(split(histLastPops,histLastPops$sysYear),FUN=function(state_slice){ 
     ggplot(state_slice, aes(sample =  sklogpop)) + 
         stat_qq(size=0.3, distribution = qnorm, dparams = list(
                           mean=state_slice$meanLog[1],
                           sd=state_slice$sdLog[1])) +
         geom_abline(slope = 1) +
         scale_x_continuous(name = "", labels = customLabels, breaks = customBreaks) +
         scale_y_continuous(name = "", labels = customLabels, breaks = customBreaks) +
         ggtitle(unique(state_slice$sysYear)) +
         theme_gibratdc() +
         theme(axis.title = element_blank())
 })
 
 grid.arrange(grobs = qqPlots, bottom = "Population (theoretical)",
              left = "Population (observed)",
              nrow=1)
```

