library(shiny)

shinyUI(pageWithSidebar(
    headerPanel("Gibrat Simulator", tags$head(includeScript("www/analytics.js"))),
    sidebarPanel(
        selectInput(inputId = 'dataset', label = "Choose country",
                    multiple = FALSE,
                    choices = c("South Africa", "Brazil", "Russia", "India", "China", "USA", "France")),
        tags$hr(),
        selectInput("timeColumnSelected", "Time columns :",choices="", multiple=TRUE, selectize=TRUE)
       
    ),
    mainPanel(
    tabsetPanel(
        tabPanel("Base data", dataTableOutput('data')),
        tabPanel("Top 10", dataTableOutput('top10')),
        tabPanel("City Size Classes", 
                 selectInput("date", "Date", choices=c("Last Census",
                                                       "Last Census - 1",
                                                       "Last Census - 2"), 
                             multiple=FALSE, 
                             selected="Last Census"), 
                  dataTableOutput('sizeClasses')),
        tabPanel("Zipf", 
                 selectInput("date", "Date", choices=c("Last Census",
                                                       "Last Census - 1",
                                                       "Last Census - 2"), 
                             multiple=FALSE, 
                             selected="Last Census"),
                 plotOutput('plotZipf'),
                 h3("Parameters of a fitted power-law distribution"),
                 tableOutput('estimZipf')),
        tabPanel("LogNormal", 
                 selectInput("date", "Date", choices=c("Last Census",
                                                       "Last Census - 1",
                                                       "Last Census - 2"), 
                             multiple=FALSE, 
                             selected="Last Census"),
                 plotOutput('plotLognormal'),
                 h3("Parameters of a fitted lognormal distribution"),
                 tableOutput('estimLognormal'),
                 h4("Computation can be long, be patient..."),
                "cf. Gillespie C. S., 2015, Fitting heavy tailed distributions : 
                 the poweRlaw package, Journal of Statistical Software, Vol. 64, Issue 2."),
        tabPanel("Transition Matrices", 
                 column(6,selectInput("dateinitial", "Initial Date", choices=c("Last Census",
                                                                      "Last Census - 1",
                                                                      "Last Census - 2"), 
                             multiple=FALSE, 
                             selected="Last Census - 1")),
                 column(6,selectInput("datefinal", "Finale Date", choices=c("Last Census",
                                                                   "Last Census - 1",
                                                                   "Last Census - 2"), 
                             multiple=FALSE, 
                             selected="Last Census")),
                 tableOutput('transitionMatrix')),
        tabPanel("Growth",
                 tags$h4("Observed"),
                 dataTableOutput('growthTable'),
                 tags$h4('Average yearly growth rate'),
                 plotOutput("growthPlot"),
                 downloadButton(outputId="dlButton", label="Download table")),
        tabPanel("Gibrat Simulation",
                 numericInput(inputId="nbReplications", label="Number of replications", value=10, min=5, max=100, step=5 ),
                 tags$hr(),
                 actionButton(inputId="runSim", label="Run simulation"),
                 conditionalPanel(condition="$('html').hasClass('shiny-busy')",
                                  tags$div(style="float:left;",
                                           tags$img(src="loading-gif-animation.gif",height=50,width=50)),
                                  h4("Computation can be long, be patient...")),
                 plotOutput('gibratRankSize'),
                 downloadButton(outputId="simresultDL", label="Download simulations results")),
        tabPanel("Correlations", tableOutput('correlations')),
        tabPanel("About", includeMarkdown(path="README.md"))
        
    )
    )
))
